package eql

import (
	"bufio"
	"compress/gzip"
	"encoding/json"
	"os"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
)

// The translated-EQL corpus holds the EQL produced by faithfully translating a
// 100k+ Sigma rule corpus (scraped real detection rules + generated complex
// rules) to EQL. Committed gzipped/LFS; regenerated by `make rules-corpus`.
const translatedEQLPath = "testdata/generated/sigma_rules_translated_eql.jsonl.gz"

// TestSigmaTranslatedEQLCorpus re-parses every EQL query derived from the 100k+
// Sigma rule corpus, asserting the parser handles real-rule-derived EQL at
// scale with zero panics and well-formed conditions.
func TestSigmaTranslatedEQLCorpus(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping translated-EQL corpus in short mode")
	}
	skipIfLFSPointer(t, translatedEQLPath)

	f, err := os.Open(translatedEQLPath)
	if err != nil {
		if os.IsNotExist(err) {
			t.Skipf("translated-EQL corpus not available at %s — run 'make rules-corpus'", translatedEQLPath)
		}
		t.Fatalf("open: %v", err)
	}
	defer f.Close()
	gz, err := gzip.NewReader(f)
	if err != nil {
		t.Fatalf("gzip: %v", err)
	}
	defer gz.Close()

	type entry struct {
		Query string `json:"query"`
	}

	ch := make(chan string, 1024)
	var total, clean, panics, malformed int64
	var wg sync.WaitGroup
	for i := 0; i < 8; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for q := range ch {
				func() {
					defer func() {
						if r := recover(); r != nil {
							atomic.AddInt64(&panics, 1)
						}
					}()
					res := ExtractConditions(q)
					atomic.AddInt64(&total, 1)
					if len(res.Errors) == 0 {
						atomic.AddInt64(&clean, 1)
					}
					for _, c := range res.Conditions {
						if c.Field == "" || c.Operator == "" {
							atomic.AddInt64(&malformed, 1)
						}
					}
				}()
			}
		}()
	}

	sc := bufio.NewScanner(gz)
	sc.Buffer(make([]byte, 0, 64*1024), 16*1024*1024)
	n := 0
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" {
			continue
		}
		var e entry
		if json.Unmarshal([]byte(line), &e) != nil {
			continue
		}
		ch <- e.Query
		n++
	}
	close(ch)
	wg.Wait()
	if err := sc.Err(); err != nil {
		t.Fatalf("scan: %v", err)
	}

	t.Logf("translated-EQL corpus: %d queries, clean=%d panics=%d malformed=%d", total, clean, panics, malformed)
	if n < 1 {
		t.Fatal("corpus was empty")
	}
	if panics > 0 {
		t.Errorf("parser panicked on %d translated queries", panics)
	}
	if malformed > 0 {
		t.Errorf("%d malformed conditions (empty field/operator)", malformed)
	}
	// This EQL was emitted by the translator and must parse cleanly.
	if rate := float64(clean) * 100 / float64(total); rate < 99.9 {
		t.Errorf("clean-parse rate %.2f%% below 99.9%%", rate)
	}
}
